---
apiVersion: v1
kind: Pod
metadata:
  name: multitool
  labels:
    app: multitool
spec:
  containers:
    - name: multitool
      imagePullPolicy: IfNotPresent
      image: praqma/network-multitool:fedora
