---
apiVersion: v1
kind: Service
metadata:
  name: service-app
spec:
  selector:
    group: app
  ports:
    {{- with .Values.appservice}}
    - name: web
      port: {{ listening-port | default "80" }}
      targetPort: app-web-port
    {{- end }}
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: service-db
spec:
  selector:
    group: db
  ports:
    {{- with .Values.db}}
    - name: db
      port: {{ listening-port | default "5432" }}
      targetPort: {{ listening-port | default "5432" }}
    {{- end }}
  type: ClusterIP

