---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.db.pg-pass | default "postgres" }} 
  POSTGRES_USER: {{ .Values.db.pg-user | default "postgres" }} 